const OLLAMA_DEFAULT_URL = 'http://127.0.0.1:11434';
const DEFAULT_MODEL_NAME = 'HammerAI/mn-mag-mell-r1:12b-q4_K_M';
const DATA_VERSION = 1;

const CHARACTER_BUILDER_TIMEOUT_MS = 120000;
const CHARACTER_BUILDER_TEMPERATURE = 0.9;
const CHARACTER_BUILDER_MAX_TOKENS = 2048;
const CHARACTER_BUILDER_CTX = 4096;

const BOT_BUILDER_TOKEN_MULTIPLIER = 1.5;
const BOT_BUILDER_CTX_MULTIPLIER = 2;

// Models that were previously shipped as Aria defaults.
// ONLY exact former defaults — never generic community model names.
const KNOWN_OLD_DEFAULT_MODELS = [
  'llama3:latest',
  'llama3:8b'
];

module.exports = { OLLAMA_DEFAULT_URL, DEFAULT_MODEL_NAME, DATA_VERSION, KNOWN_OLD_DEFAULT_MODELS, CHARACTER_BUILDER_TIMEOUT_MS, CHARACTER_BUILDER_TEMPERATURE, CHARACTER_BUILDER_MAX_TOKENS, CHARACTER_BUILDER_CTX, BOT_BUILDER_TOKEN_MULTIPLIER, BOT_BUILDER_CTX_MULTIPLIER };
